# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for all updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Group minor and patch updates
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/*' # Exclude type definitions from grouping for better clarity
    # Handle major updates separately (they won't be grouped)
    # Limit the number of open PRs for major updates
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'deps'
      include: 'scope'
