name: build-express
on:
  pull_request:
    paths:
      - 'packages/express/**'
      - '.github/workflows/build-express.yml'
jobs:
  build-express-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Upload to DO
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: npm install -g yarn
      - run: npm install -g lerna
      - run: npm install -g typescript
      - run: lerna bootstrap
      - name: Build
        run: |
          printf "${{ secrets.VUE_ENV }}" > ./packages/vue/.env.production
          yarn build
      # todo: add some tests haha
