name: deploy-vue
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for deploying Vue app'
        required: true
        default: 'Manual deployment'
jobs:
  deploy-vue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Configure SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Install dependencies
        run: yarn install

      - name: Set production environment
        run: printf "${{ secrets.VITE_ENV }}" > ./packages/vue/.env.production

      - name: Build
        run: yarn build

      - name: Create build info
        run: |
          BUILD_INFO="Build created on $(date) from commit ${{ github.sha }}\n"
          BUILD_INFO+="Triggered by ${{ github.actor }} via ${{ github.event_name }}\n"
          BUILD_INFO+="Reason: ${{ github.event.inputs.reason }}\n"
          echo -e "$BUILD_INFO" > ./packages/vue/dist/buildinfo.md

      - name: Deploy to server
        run: |
          vcount=$(ssh ${{ secrets.DO_USERNAME }}@eduquilt.com ls -1v /home/skuilder/dist/vue/ | grep -E '^[0-9]+$' | tail -n1 || echo 0)
          newversion=$(($vcount+1))
          echo "Creating directory version $newversion..."
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir -p /home/skuilder/dist/vue/$newversion
          echo "Syncing files to server..."
          rsync -rl --delete ./packages/vue/dist/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/vue/$newversion
          echo "Setting symlink to new version..."
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com ln -sfn /home/skuilder/dist/vue/$newversion /home/skuilder/www
          echo "Deployment complete to version $newversion"
