name: deploy-express
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} on commit ${{ github.SHA }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: SSH to DO
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Build
        run: |
          npm install -g yarn@1.22.17
          npm install -g lerna@3.22.1
          lerna bootstrap
          cd ./packages/express
          yarn remove @types/jest
          cd ../..
          yarn build
      - name: Deploy and run
        run: |
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir /home/skuilder/dist/express/${{ steps.get_version.outputs.VERSION }}
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com mkdir /home/skuilder/dist/express/${{ steps.get_version.outputs.VERSION }}/assets
          rsync -rl ./packages/express/dist/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/express/${{ steps.get_version.outputs.VERSION }}
          rsync -rl ./packages/express/assets/ ${{ secrets.DO_USERNAME }}@eduquilt.com:/home/skuilder/dist/express/${{ steps.get_version.outputs.VERSION }}/assets
          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com ln -sfn /home/skuilder/dist/express/${{ steps.get_version.outputs.VERSION }} /home/skuilder/api

          ssh ${{ secrets.DO_USERNAME }}@eduquilt.com rm /home/skuilder/.env.development.local
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo VERSION=${{ steps.get_version.outputs.VERSION }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_ADMIN=${{ secrets.COUCHDB_ADMIN }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_PASSWORD=${{ secrets.COUCHDB_PASSWORD }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_PROTOCOL=${{ secrets.COUCHDB_PROTOCOL }} >> /home/skuilder/.env.development.local'
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_SERVER=${{ secrets.COUCHDB_SERVER }} >> /home/skuilder/.env.development.local'

          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo ${{ secrets.DO_PASSWORD }} | sudo -S systemctl restart eqExpress'

          sleep 10s
          if curl https://eduquilt.com/express | grep -q ${{ steps.get_version.outputs.VERSION }}; then
              echo "Success. Current version found in production"
              exit 0
          else
              echo "Error! Current version not reported by production."
              exit 1
          fi
      # todo: toss a buildinfo.md file into the (target build) folder, linking PR, listing time, logging build errors, etc
