name: deploy-service-file
on:
  pull_request:
    branches:
      - master
    paths:
      - '.deployment/eqExpress.service'
jobs:
  deploy_service_file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: auth step
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: |
          echo "deploying updated eqExpress.service file in place of prior"
          scp .deployment/eqExpress.service ${{ secrets.DO_USERNAME }}@eduquilt.com:~/eqExpress.service
          echo "restarting the service"
          ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo ${{ secrets.DO_PASSWORD }} | sudo -S systemctl restart eqExpress'
